# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.19.2
# Mod Properties
mod_version=1.0
maven_group=me.sootysplash.swap
archives_base_name=attribute-swap-indicator
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.148.0+26.1.2
modmenu_version=18.0.0-alpha.8
clothconfig_version=26.1.154
